name: BMPL
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - jupyter
  - numpy=1.20
  - scipy=1.6
  - matplotlib=3.4
  - pandas=1.2
  - xarray=0.18
  - astropy=4.2
  - sunpy=3.0
  - plasmapy=0.6
  - pytest=6.2
  - hypothesis=6.14
  - h5py=3.2
  - pip=21.1
  - pip:
    - spyder
